# Generated by Django 3.2.4 on 2021-06-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_order_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(verbose_name='Время заказа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.DateTimeField(verbose_name='Время'),
        ),
    ]
