# Generated by Django 3.2.4 on 2021-06-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210619_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.AddField(
            model_name='question',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='guest', max_length=100, verbose_name='От кого'),
        ),
    ]
