# Generated by Django 3.2.4 on 2021-06-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_order_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='surname',
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
    ]
