# Generated by Django 3.2.4 on 2021-06-28 16:28

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210622_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='Пользователь', max_length=100, verbose_name='От кого'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+79999999999', max_length=128, region=None, verbose_name='Телефон'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
